# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-17 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'movie_tags',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='电影名称')),
                ('cover', models.CharField(max_length=64, verbose_name='封面')),
                ('actor', models.CharField(max_length=32, verbose_name='主演')),
                ('type', models.CharField(max_length=10, verbose_name='类型')),
                ('summarize', models.CharField(max_length=255, verbose_name='简介')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'movie',
                'ordering': ['-create_time'],
            },
        ),
    ]
